### ISSUE TITLE
Setting up project

### ISSUE THREAD

**Issue by leslie-alldridge** [bkawan/django-auth-with-social#1]
Hi @bkawan  is there a step i'm doing wrong?

When trying to run migrations my terminal prints out the following 

```
$ pipenv run python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Beast\.virtualenvs\django-auth-with-social-TCjP-8Ve\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Beast\.virtualenvs\django-auth-with-social-TCjP-8Ve\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "C:\Users\Beast\.virtualenvs\django-auth-with-social-TCjP-8Ve\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Beast\.virtualenvs\django-auth-with-social-TCjP-8Ve\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Beast\.virtualenvs\django-auth-with-social-TCjP-8Ve\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Beast\.virtualenvs\django-auth-with-social-TCjP-8Ve\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'allauth'
```

Thank you

**Comment by bkawan** [comment]
@leslie-alldridge 
Sorry for late reply.

Can you please install django-allauth? I have updated the requirements which I forgot earlier. Let me know if it helps or other issues. Thank you
